# Generated by Django 3.0.6 on 2021-04-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=1000)),
                ('blog_description', models.CharField(max_length=10000)),
                ('blog_image', models.ImageField(blank=True, upload_to='profileimg')),
            ],
        ),
    ]
